apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: fuse-application
  name: fuse-application-s2i
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'fuse-application:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/hxia209/hello-fuseApp'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'fuse7-java-openshift:1.5'
        namespace: camel-ws
    type: Source
