spec:
  template:
    spec:
      containers:
        - env:
          - name: SPRING_ACTIVEMQ_BROKER_URL
            valueFrom:
            configMapKeyRef:
              name: amq-broker-config
              key: SPRING_ACTIVEMQ_BROKER_URL
          - name: SPRING_ACTIVEMQ_USER
            valueFrom:
            configMapKeyRef:
              name: amq-broker-config
              key: SPRING_ACTIVEMQ_USER
          - name: SPRING_ACTIVEMQ_PASSWORD
            valueFrom:
            configMapKeyRef:
              name: amq-broker-config
              key: SPRING_ACTIVEMQ_PASSWORD
          resources:
            requests:
              cpu: "0.2"
              memory: 256Mi
            limits:
              cpu: "1.0"
              memory: 256Mi
